name: Rust

on:
  push:
    branches: [main]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  checks:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: psibi/install-action@c72791d81af61349f8c1870780d45f7348ee1871
      with:
        tool: agave@2.2.18,just
    - name: Test
      run: just pwd
    - name: Test agave
      run: |
        solana --version
        cargo-build-sbf --version
        cargo-test-sbf --version
    - name: More test
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        echo var dir check
        ls -lah /var
        echo private dir check
        ls -lah /private
